baseurl: https://clarewest.github.io/blog/
title: Clare's Blog
author: CE West
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
permalinks:
  posts: :slug
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Clare's Blog
  uselatex: yes
  twitter: claree_west
  logofile: images/favicon.png
  commentsrepo: clarewest/blog-comments
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
 #   - name: About
#      url: /about/
 #     weight: 2
    - name: GitHub
      url: https://github.com/clarewest
      weight: 2
    - name: Twitter
      url: https://twitter.com/claree_west
      weight: 3
    - name: Website
      url: https://clarewest.github.io
 #   - name: Subscribe
#      url: /index.xml
#      weight: 5
